import {
  AppState,
  addWeeks,
  mondayOf,
  ensureUniquePriorities,
  DEFAULT_SIZE_RANGES,
  uniqCatalogNames,
  containerNameFromBacklog,
} from "./model";

const S0 = mondayOf();
const S1 = addWeeks(S0, 1);
const S2 = addWeeks(S0, 2);
const S3 = addWeeks(S0, 3);
const S4 = addWeeks(S0, 4);
const S6 = addWeeks(S0, 6);
const S8 = addWeeks(S0, 8);

/** Demo: mix of 1 / 2 / 3+ teams with per-team start dates */
const SEED_RAW: AppState = {
  version: 3,
  startDate: S0,
  sizeRanges: {
    S: { ...DEFAULT_SIZE_RANGES.S },
    M: { ...DEFAULT_SIZE_RANGES.M },
    L: { ...DEFAULT_SIZE_RANGES.L },
  },
  teams: [
    {
      id: "platform",
      name: "Platform",
      capacityPw: 4,
      color: "#d60000",
    },
    {
      id: "mobile",
      name: "Mobile",
      capacityPw: 3,
      color: "#455a64",
    },
    {
      id: "data",
      name: "Data & Analytics",
      capacityPw: 2.5,
      color: "#737373",
    },
    {
      id: "crm",
      name: "CRM / Sales Tech",
      capacityPw: 3.5,
      color: "#e65100",
    },
  ],
  customers: [],
  executors: [],
  projects: [],
  products: [],
  items: [
    {
      id: "p2",
      title: "Мобильный чекаут v2",
      type: "product",
      backlog: "Mobile",
      assignments: [{ teamId: "mobile", size: "M", workStartDate: S0 }],
      status: "ready",
      owner: "Маша Л.",
      assignee: "Ира М.",
      reach: 5000,
      impact: 2,
      confidence: 0.8,
      manualRank: null,
      cashFlow12m: 12_400_000,
      roi12m: 8_200_000,
    },
    {
      id: "j4",
      title: "Интеграция телефонии для отдела продаж",
      type: "project",
      backlog: "ЛК B2B",
      assignments: [{ teamId: "crm", size: "S", workStartDate: S1 }],
      status: "ready",
      owner: "Сергей М.",
      assignee: "Никита П.",
      reach: 40,
      impact: 1,
      confidence: 0.7,
      manualRank: null,
      cashFlow12m: 3_600_000,
      roi12m: 2_100_000,
    },
    {
      id: "p6",
      title: "Push-уведомления и deep links",
      type: "product",
      backlog: "Mobile",
      assignments: [{ teamId: "mobile", size: "S", workStartDate: S4 }],
      status: "idea",
      owner: "Маша Л.",
      assignee: "",
      reach: 8000,
      impact: 1,
      confidence: 0.6,
      manualRank: null,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "j6",
      title: "Дашборд KPI для совета директоров",
      type: "project",
      backlog: "Exec",
      assignments: [{ teamId: "data", size: "S", workStartDate: S0 }],
      status: "ready",
      owner: "Павел Р.",
      assignee: "Лена Ф.",
      reach: 12,
      impact: 2,
      confidence: 0.9,
      notes: "Нужен к ближайшему совету",
      manualRank: null,
      cashFlow12m: null,
      roi12m: 450_000,
    },
    {
      id: "p5",
      title: "Админ-панель ролей и аудита",
      type: "product",
      backlog: "Platform",
      assignments: [{ teamId: "platform", size: "S", workStartDate: S6 }],
      status: "idea",
      owner: "Аня К.",
      assignee: "",
      reach: 25,
      impact: 0.5,
      confidence: 0.85,
      manualRank: null,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "p1",
      title: "Единый каталог цен и остатков",
      type: "product",
      backlog: "Commerce",
      assignments: [
        { teamId: "platform", size: "M", workStartDate: S0 },
        { teamId: "data", size: "M", workStartDate: S3 },
      ],
      status: "in_progress",
      owner: "Аня К.",
      assignee: "Коля Д.",
      reach: 10000,
      impact: 3,
      confidence: 0.8,
      notes: "Data стартует после первых API Platform",
      manualRank: null,
      cashFlow12m: 28_000_000,
      roi12m: 19_500_000,
    },
    {
      id: "j1",
      title: "Внедрение EDI для крупного B2B-клиента",
      type: "project",
      backlog: "Delivery",
      assignments: [
        { teamId: "platform", size: "M", workStartDate: S1 },
        { teamId: "crm", size: "S", workStartDate: S4 },
      ],
      status: "ready",
      owner: "Игорь С.",
      assignee: "Саша В.",
      reach: 1,
      impact: 2,
      confidence: 0.85,
      notes: "CRM — онбординг после ядра EDI",
      manualRank: null,
      cashFlow12m: 5_200_000,
      roi12m: null,
    },
    {
      id: "j2",
      title: "Пилот Launchpad: клинический портал",
      type: "project",
      backlog: "Launchpad",
      assignments: [
        { teamId: "mobile", size: "M", workStartDate: S2 },
        { teamId: "platform", size: "S", workStartDate: S2 },
      ],
      status: "ready",
      owner: "Денис В.",
      assignee: "",
      reach: 200,
      impact: 2,
      confidence: 0.7,
      notes: "Обе команды стартуют одновременно",
      manualRank: null,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "j3",
      title: "Миграция отчётности клиента X на DWH",
      type: "project",
      backlog: "Data",
      assignments: [
        { teamId: "data", size: "M", workStartDate: S1 },
        { teamId: "platform", size: "S", workStartDate: S0 },
      ],
      status: "ready",
      owner: "Павел Р.",
      assignee: "Лена Ф.",
      reach: 5,
      impact: 1,
      confidence: 0.75,
      notes: "Platform — пайплайн выгрузки раньше Data",
      manualRank: null,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "p4",
      title: "Сквозная воронка лида → сделка",
      type: "product",
      backlog: "CRM",
      assignments: [
        { teamId: "crm", size: "M", workStartDate: S0 },
        { teamId: "platform", size: "S", workStartDate: S2 },
        { teamId: "mobile", size: "S", workStartDate: S6 },
      ],
      status: "in_progress",
      owner: "Оля Т.",
      assignee: "Миша К.",
      reach: 3000,
      impact: 3,
      confidence: 0.8,
      notes: "Mobile подключается после событий Platform",
      manualRank: null,
      cashFlow12m: 15_800_000,
      roi12m: 11_200_000,
    },
    {
      id: "j5",
      title: "Compliance-пакет HIPAA для продукта Y",
      type: "project",
      backlog: "Security",
      assignments: [
        { teamId: "platform", size: "M", workStartDate: S3 },
        { teamId: "data", size: "S", workStartDate: S4 },
        { teamId: "mobile", size: "S", workStartDate: S8 },
      ],
      status: "blocked",
      owner: "Игорь С.",
      assignee: "",
      reach: 500,
      impact: 2,
      confidence: 0.9,
      notes: "Ждём юристов; старты сдвинуты",
      manualRank: null,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "p3",
      title: "Рекомендации в поиске (ML)",
      type: "product",
      backlog: "Growth",
      assignments: [
        { teamId: "data", size: "L", workStartDate: S2 },
        { teamId: "platform", size: "S", workStartDate: S6 },
        { teamId: "mobile", size: "S", workStartDate: S8 },
      ],
      status: "idea",
      owner: "Катя Н.",
      assignee: "Дима Р.",
      reach: 15000,
      impact: 2,
      confidence: 0.5,
      notes: "Serving и UI после модели",
      manualRank: null,
      cashFlow12m: 22_000_000,
      roi12m: 9_750_000,
    },
  ],
};

/** Unique priorities + catalogs from demo names */
export const SEED: AppState = {
  ...SEED_RAW,
  customers: uniqCatalogNames(SEED_RAW.items.map((i) => i.owner)),
  executors: uniqCatalogNames(SEED_RAW.items.map((i) => i.assignee)),
  projects: uniqCatalogNames(
    SEED_RAW.items
      .filter((i) => i.type === "project")
      .map((i) => containerNameFromBacklog(i.backlog))
  ),
  products: uniqCatalogNames(
    SEED_RAW.items
      .filter((i) => i.type === "product")
      .map((i) => containerNameFromBacklog(i.backlog))
  ),
  items: ensureUniquePriorities(SEED_RAW.items),
};
