import {
  AppState,
  MIGRATION_CLEARED_DEMAND_TEAMS,
  MIGRATION_SEEDED_TEAM_ROSTER,
  Team,
  applyComputedTeamCapacities,
  containerNameFromBacklog,
  ensureUniquePriorities,
  makeSeedTeamMembers,
  syncTeamRoster,
  uniqCatalogNames,
} from "./model";

/** ISO start for the Oct 2026 prioritization pack (all assignments). */
export const PORTFOLIO_START = "2026-10-01";

/** Applied once to live/cloud state; rollback keeps this from re-applying. */
export const PORTFOLIO_PACK_ID = "xlsx-prio-2026-10-v4";
/** Previous packs — load path fully replaces seed (not a status-only patch). */
export const PORTFOLIO_PACK_PREV = "xlsx-prio-2026-10-v3";
export const PORTFOLIO_PACK_V2 = "xlsx-prio-2026-10-v2";
export const PORTFOLIO_PACK_V1 = "xlsx-prio-2026-10";
export const PORTFOLIO_PACK_ROLLED_BACK = "xlsx-prio-2026-10-rolled-back";

const START = PORTFOLIO_START;

const SEED_RAW: AppState = {
  version: 3,
  startDate: START,
  sizeRanges: {
    XS: { min: 1, max: 5 },
    S: { min: 5, max: 10 },
    M: { min: 10, max: 20 },
    L: { min: 20, max: 40 },
    XL: { min: 40, max: 80 },
    XXL: { min: 80, max: 160 },
  },
  portfolioNotes: "",
  changeLog: [],
  portfolioPack: PORTFOLIO_PACK_ID,
  clearedDemandTeams: MIGRATION_CLEARED_DEMAND_TEAMS,
  teamRosterSeeded: MIGRATION_SEEDED_TEAM_ROSTER,
  teams: [
    {
      id: "data-office",
      name: "Data-office",
      capacityPw: 3,
      color: "#d60000",
    },
    {
      id: "crm",
      name: "CRM",
      capacityPw: 3,
      color: "#455a64",
    },
    {
      id: "crm-prod-prorabotka",
      name: "CRM · прод. проработка",
      capacityPw: 3,
      color: "#e65100",
    },
    {
      id: "crm-analitika",
      name: "CRM · аналитика",
      capacityPw: 3,
      color: "#2e7d32",
    },
    {
      id: "crm-razrabotka",
      name: "CRM · разработка",
      capacityPw: 3,
      color: "#1565c0",
    },
    {
      id: "tbd",
      name: "TBD",
      capacityPw: 3,
      color: "#6a1b9a",
    },
    {
      id: "sayt-lk",
      name: "Сайт ЛК",
      capacityPw: 3,
      color: "#00838f",
    },
    {
      id: "crm-touch",
      name: "CRM Touch",
      capacityPw: 3,
      color: "#c62828",
    },
    {
      id: "sayt",
      name: "Сайт",
      capacityPw: 3,
      color: "#546e7a",
    },
    {
      id: "oms-arm-analitika",
      name: "OMS/ARM · аналитика",
      capacityPw: 3,
      color: "#ef6c00",
    },
    {
      id: "oms-arm-razrabotka",
      name: "OMS/ARM · разработка",
      capacityPw: 3,
      color: "#558b2f",
    },
    {
      id: "oms-arm",
      name: "OMS/ARM",
      capacityPw: 3,
      color: "#283593",
    },
    {
      id: "sayt-vybor-analitika",
      name: "Сайт Выбор · аналитика",
      capacityPw: 3,
      color: "#ad1457",
    },
    {
      id: "sayt-vybor-razrabotka",
      name: "Сайт Выбор · разработка",
      capacityPw: 3,
      color: "#00695c",
    },
    {
      id: "sayt-vybor",
      name: "Сайт Выбор",
      capacityPw: 3,
      color: "#5d4037",
    },
    {
      id: "fd-analitika",
      name: "ФД · аналитика",
      capacityPw: 3,
      color: "#37474f",
    },
    {
      id: "fd-oplaty",
      name: "ФД · оплаты",
      capacityPw: 3,
      color: "#f9a825",
    },
    {
      id: "fd-dokumenty",
      name: "ФД · документы",
      capacityPw: 3,
      color: "#0277bd",
    },
    {
      id: "fd",
      name: "ФД",
      capacityPw: 3,
      color: "#7b1fa2",
    },
    {
      id: "1s-razrabotka",
      name: "1С · разработка",
      capacityPw: 3,
      color: "#009688",
    },
    {
      id: "1s",
      name: "1С",
      capacityPw: 3,
      color: "#ff7043",
    },
    {
      id: "sayt-oformlenie-analitika",
      name: "Сайт Оформление · аналитика",
      capacityPw: 3,
      color: "#5c6bc0",
    },
    {
      id: "sayt-oformlenie-razrabotka",
      name: "Сайт Оформление · разработка",
      capacityPw: 3,
      color: "#8d6e63",
    },
    {
      id: "sayt-oformlenie",
      name: "Сайт Оформление",
      capacityPw: 3,
      color: "#26a69a",
    },
    {
      id: "sayt-lk-b2b",
      name: "Сайт ЛК/B2B",
      capacityPw: 3,
      color: "#ec407a",
    },
    {
      id: "sayt-vybor-i-navigacia",
      name: "Сайт Выбор и навигация",
      capacityPw: 3,
      color: "#78909c",
    },
    {
      id: "sayt-lk-b2b-frontend",
      name: "Сайт ЛК/B2B · frontend",
      capacityPw: 3,
      color: "#9ccc65",
    },
    {
      id: "sayt-lk-b2b-sistemnyy-analitik",
      name: "Сайт ЛК/B2B · системный аналитик",
      capacityPw: 3,
      color: "#ba68c8",
    },
    {
      id: "sayt-lk-b2b-backend",
      name: "Сайт ЛК/B2B · backend",
      capacityPw: 3,
      color: "#4dd0e1",
    },
    {
      id: "analitika",
      name: "Аналитика",
      capacityPw: 3,
      color: "#ffb74d",
    },
    {
      id: "kb",
      name: "КБ",
      capacityPw: 3,
      color: "#90a4ae",
    },
    {
      id: "dwh",
      name: "DWH",
      capacityPw: 3,
      color: "#a1887f",
    },
    {
      id: "oms",
      name: "OMS",
      capacityPw: 3,
      color: "#d60000",
    },
    {
      id: "sayt-lk-analitika",
      name: "Сайт ЛК · аналитика",
      capacityPw: 3,
      color: "#455a64",
    },
    {
      id: "sayt-lk-razrabotka",
      name: "Сайт ЛК · разработка",
      capacityPw: 3,
      color: "#e65100",
    },
    {
      id: "oms-arhitektura",
      name: "OMS · архитектура",
      capacityPw: 3,
      color: "#2e7d32",
    },
  ],
  customers: [],
  executors: [],
  projects: [],
  products: [],
  items: [
    {
      id: "x001",
      title: "Налажены сквозная аналитика и SLA (командой Data-office)",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 1,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x002",
      title: "Оптимизировано управление исполнителями и рабочими очередями",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: CRM разраб. - M CRM аналитика - M",
      manualRank: 2,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x003",
      title: "Выполнена продуктовая проработка, архитектура и аналитика по реализации одной сущности обращения (претензия + ФОК)",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: CRM прод. проработка - S",
      manualRank: 3,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x004",
      title: "Сбор CSAT по закрытым обращениям (к обсуждению с клиентским опытом и сайтом)",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - S разраб. - M",
      manualRank: 4,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x005",
      title: "Реализация поиска на странице обращений на сайте",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 5,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x006",
      title: "Реализовано повторное открытие обращения с выбором причины",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: CRM разраб. - M CRM аналитика - M Сайт разраб. - S Сайт аналитика - S",
      manualRank: 6,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x007",
      title: "Возможность обмена файлами внутри обращения с клиентами",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: CRM разраб. - XS CRM аналитика - XS Сайт разраб. - L Сайт аналитика - M",
      manualRank: 7,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x008",
      title: "Возможность обмена сообщениями внутри обращения с клиентами",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: CRM разраб. - S CRM аналитика - S Сайт разраб. - S Сайт аналитика - S",
      manualRank: 8,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x009",
      title: "Подключены проактивные уведомления (Клиент получает уведомления в предпочтительном канале)",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: CRM разраб. - L CRM аналитика - L Сайт разраб. - S Сайт аналитика - S",
      manualRank: 9,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x010",
      title: "Реализована админка редактирования обращений на сайте (к обсуждению)",
      type: "project",
      backlog: "Единая операционная модель",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: CRM разраб. - S CRM аналитика - S Сайт разраб. - S Сайт аналитика - S",
      manualRank: 10,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x011",
      title: "Вариант HLD 1.1. Оркестрация на OMS (Своими силами) — OMS/ARM",
      type: "project",
      backlog: "Подарочные сертификаты",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - L разраб. - XL",
      manualRank: 11,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x012",
      title: "Вариант HLD 1.1. Оркестрация на OMS (Своими силами) — САЙТ Выбор",
      type: "project",
      backlog: "Подарочные сертификаты",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - XL разраб. - XXL",
      manualRank: 12,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x013",
      title: "Вариант HLD 1.1. Оркестрация на OMS (Своими силами) — ФД",
      type: "project",
      backlog: "Подарочные сертификаты",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - L оплаты - L документы - L",
      manualRank: 13,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x014",
      title: "Вариант HLD 1.1. Оркестрация на OMS (Своими силами) — 1C",
      type: "project",
      backlog: "Подарочные сертификаты",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: разраб. - L",
      manualRank: 14,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x015",
      title: "Вариант HLD 2.1. (Силами подрядчика) — OMS/ARM",
      type: "project",
      backlog: "Подарочные сертификаты",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - L разраб. - XL",
      manualRank: 15,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x016",
      title: "Вариант HLD 2.1. (Силами подрядчика) — САЙТ Выбор",
      type: "project",
      backlog: "Подарочные сертификаты",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - L разраб. - XXL",
      manualRank: 16,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x017",
      title: "Вариант HLD 2.1. (Силами подрядчика) — ФД",
      type: "project",
      backlog: "Подарочные сертификаты",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - L оплаты - L документы - L",
      manualRank: 17,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x018",
      title: "Вариант HLD 2.1. (Силами подрядчика) — 1C",
      type: "project",
      backlog: "Подарочные сертификаты",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: разраб. - L",
      manualRank: 18,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x019",
      title: "Mobile ID успешно внедрен на сайте.",
      type: "project",
      backlog: "Mobile ID (SIM Push)",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 19,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x020",
      title: "Mobile ID успешно внедрен в мобильном приложении iOS.",
      type: "project",
      backlog: "Mobile ID (SIM Push)",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 20,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x021",
      title: "Mobile ID успешно внедрен в мобильном приложении Android.",
      type: "project",
      backlog: "Mobile ID (SIM Push)",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 21,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x022",
      title: "SMS используется только как резервный сценарий.",
      type: "project",
      backlog: "Mobile ID (SIM Push)",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 22,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x023",
      title: "Получен прогнозируемый экономический эффект.",
      type: "project",
      backlog: "Mobile ID (SIM Push)",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 23,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x024",
      title: "Не ухудшена текущая конверсия регистрации и авторизации.",
      type: "project",
      backlog: "Mobile ID (SIM Push)",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 24,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x025",
      title: "Среднее время авторизации сокращено относительно текущего процесса.",
      type: "project",
      backlog: "Mobile ID (SIM Push)",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 25,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x026",
      title: "Кнопка «Купить в кредит» отображается только у B2B-клиентов из выборки при выполнении условий банка и ВИ. В остальных случаях - скрыта или заблокирована",
      type: "project",
      backlog: "Кредитование Б2Б",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - M разраб. - XS",
      manualRank: 26,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x027",
      title: "Создание кредитной заявки с уникальным ID и привязкой к заказу. Данные безопасно передаются банку, переход на сайт банка и возврат на ВИ (успешный/неуспешный) работают корректно.",
      type: "project",
      backlog: "Кредитование Б2Б",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Сайт аналитика - M Сайт разраб. - L ФД аналитика - M ФД разраб. - M 1С разработка - M",
      manualRank: 27,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x028",
      title: "Банк самостоятельно проводит скоринг, информирование и подписание договора. ВИ информирует пользователя о роли банка.",
      type: "project",
      backlog: "Кредитование Б2Б",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - XS разраб. - XS",
      manualRank: 28,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x029",
      title: "ВИ не признает заказ оплаченным до официального подтверждения от банка. После получения статуса заказ передается в стандартную доставку.",
      type: "project",
      backlog: "Кредитование Б2Б",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - M разраб. - XS",
      manualRank: 29,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x030",
      title: "Корректная обработка ошибок, отказов и недоступности банка. Незавершенный заказ сохраняет возможность оплаты другим способом до истечения тайм-аута",
      type: "project",
      backlog: "Кредитование Б2Б",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: аналитика - M разраб. - XS",
      manualRank: 30,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x031",
      title: "[Q3 2026][Реализация][База] NPS + CSAT",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: уже в работе",
      manualRank: 31,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x032",
      title: "[Q32026 Реализация][База] Авто подтверждение постоплатных заказов",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: уже в работе",
      manualRank: 32,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x033",
      title: "[Q32026 Реализация][База] Сохранение корзины по снэпшотам",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 33,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x034",
      title: "[Q42026 Реализация][База] Поиск товаров по списку. Аналоги",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 34,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x035",
      title: "[Q42026 Реализация][База] [Фильтры] Фильтр по сроку доставки",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 35,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x036",
      title: "[Q42026 Реализация][База][Заказы] Редактирование логистических данных",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Аналитика OMS/ARM - M Разработка OMS/ARM - ? Аналитика Сайт - XS Разработка Сайт - ?",
      manualRank: 36,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x037",
      title: "[Q42026 Реализация][База] Скачивание заказа в xlsx",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: FE: XS",
      manualRank: 37,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x038",
      title: "[Q42026 Реализация][База] редактирования состава заказа при согласовании",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: SA: S, FE: XS, BE: S",
      manualRank: 38,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x039",
      title: "[Q42026 Реализация][База] Гибкое управление лимитами",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: РМ. Лимит на единицу товара BE: S, FE: XS Если SA потребуется, то оценка S РМ. Лимит на минимальную стоимость заказа BE: S, FE: XS SA не нужно или S",
      manualRank: 39,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x040",
      title: "[Q42026 Реализация][Прорыв] Поиск товаров по списку. Конечная стоимость товаров в корзине",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 40,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x041",
      title: "[Q42026 Реализация][Прорыв] Сервис уведомлений",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "https://docs.google.com/spreadsheets/d/1d0E0C_WLwpUFUmnqrEnMI7vpbn4dZkBlNIr9NQ1zb2E/edit?gid=0#gid=0",
      manualRank: 41,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x042",
      title: "[Q42026 Реализация][Прорыв] Статусная модель",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "https://docs.google.com/spreadsheets/d/1d0E0C_WLwpUFUmnqrEnMI7vpbn4dZkBlNIr9NQ1zb2E/edit?gid=0#gid=0",
      manualRank: 42,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x043",
      title: "[Q42026 Реализация][Прорыв] Онбординг",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: FE: M",
      manualRank: 43,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x044",
      title: "[Q42026 Реализация][Прорыв] Сквозная работа Ролевой Модели в ЮЛ",
      type: "project",
      backlog: "B2b онлайн платформа",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: BE: M, FE: XS СА: М",
      manualRank: 44,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x045",
      title: "Офферы: Автоматизация офферной политики Перевод 100% недельного планирования офферов на исполнителей в CRM - Критичные доработки систем",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: в работе Аналитика - XS Разработка CRM - S Разработка КБ - S",
      manualRank: 45,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x046",
      title: "Офферы: Автоматизация офферной политики Перевод 100% недельного планирования офферов на исполнителей в CRM - Недельный планировщик офферов - Атоматическое исполнение недельного плана",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: в работе Аналитика - L Разработка CRM - L",
      manualRank: 46,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x047",
      title: "Инициативы на КАМ (триг задачи, ОПС) Автоматическая постановка задач менеджерам по развитию клиентов (КАМ) на основе триггерных событий",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: в работе Аналитика - L Разработка CRM - M Разработка КБ - M Разработка КБ - M",
      manualRank: 47,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x048",
      title: "CJM МПР - развитие точек роста Реализовать и внедрить целевой процесс работы МпР с точками роста",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: в работе Аналитика - L Разработка CRM - L",
      manualRank: 48,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x049",
      title: "Отключить CRM от МПРов Повысить производительность МПРов на основе перехода на новое решение CRM МПР,",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: в работе Аналитика - M Разработка CRM - L",
      manualRank: 49,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x050",
      title: "CJM БДМ Сформировать единый стандарт работы в CRM для BDM",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: в работе Аналитика - XS Разработка CRM - L",
      manualRank: 50,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x051",
      title: "AO email: ЛИДЫ 1. Рост доли автооформленных заказов на 75% (с 20% до 35%)",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Аналитика - S Разработка CRM - M",
      manualRank: 51,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x052",
      title: "Маркировка писем, обработанных АО Среднее время отправки счета (СМБ) менее 15 минут при оценке от менеджеров более 4",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Аналитика - M Разработка CRM - M",
      manualRank: 52,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x053",
      title: "Автомаршрутизация 90% нелидовых обращений",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Аналитика - XS Разработка CRM - S",
      manualRank: 53,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x054",
      title: "Сервис аналитики звонков - рост CR в оформленные со звонка с тематикой покупка на 5 п.п. - рост CR в отгруженные по заказам свыше 300 тыс. руб на 1 п.п.",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Аналитика - S Разработка CRM - L (разраб от бизенса)",
      manualRank: 54,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x055",
      title: "Тендеры Разработано рабочее место тендерного отдела, сервис покрывает 90% требований тендерного отдела",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Разработка CRM - тимлид",
      manualRank: 55,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x056",
      title: "Офферы Альтернативные счета в расходке",
      type: "project",
      backlog: "Активные продажи",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Аналитика - XS Разработка OMS - S",
      manualRank: 56,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x057",
      title: "Доделать и отладить отчётность по атрибуции притока",
      type: "project",
      backlog: "ДКБ",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      manualRank: 57,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x058",
      title: "Запущен процесс работы отдела АНК через автоматические задачи 3х касаний",
      type: "project",
      backlog: "ДКБ",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: В работе",
      manualRank: 58,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x059",
      title: "Цифровой онбординг доступен для 100% новых b2b клиентов (часть уведомлений на сайте и email)",
      type: "project",
      backlog: "ДКБ",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Аналитика - XS Разработка - M",
      manualRank: 59,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x060",
      title: "Запущен процесс автоформирования ГБО на ОАП",
      type: "project",
      backlog: "ДКБ",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Аналитика - M Разработка CRM - S Разработка КБ - S",
      manualRank: 60,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x061",
      title: "Автоматизация пердачи лидов ОАП - АНК, Этап 0 и Этап 1",
      type: "project",
      backlog: "ДКБ",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: В работе",
      manualRank: 61,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x062",
      title: "Купер MVP",
      type: "project",
      backlog: "ДКБ",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Архитектура - M Аналитика OMS Аналитика ЦО Аналитика товарный каталог Разработка OMS Разработка ЦО Разработка товарный каталог",
      manualRank: 62,
      cashFlow12m: null,
      roi12m: null,
    },
    {
      id: "x063",
      title: "Запущен MVP лояльности для b2b: 1. Лендинг программы 2. 2 акции и их механика 3. Баллы и обмен баллов на промики",
      type: "project",
      backlog: "ДКБ",
      assignments: [],
      status: "ready",
      owner: "—",
      assignee: "",
      reach: 0,
      impact: 1,
      confidence: 0.7,
      notes: "Оценка из таблицы: Архитектура - M Сайт ЛК - L Сайт Оформление - M Аналитика - M",
      manualRank: 63,
      cashFlow12m: null,
      roi12m: null,
    },
  ],
};

function withSeedRosters(teams: Team[]): Team[] {
  return applyComputedTeamCapacities(
    teams.map((t) =>
      syncTeamRoster({
        ...t,
        members: t.members ?? makeSeedTeamMembers(t.id),
      })
    )
  );
}

export const SEED: AppState = {
  ...SEED_RAW,
  teams: withSeedRosters(SEED_RAW.teams),
  customers: uniqCatalogNames(SEED_RAW.items.map((i) => i.owner)),
  executors: uniqCatalogNames(SEED_RAW.items.map((i) => i.assignee)),
  projects: uniqCatalogNames(
    SEED_RAW.items
      .filter((i) => i.type === "project")
      .map((i) => containerNameFromBacklog(i.backlog))
  ),
  products: uniqCatalogNames(
    SEED_RAW.items
      .filter((i) => i.type === "product")
      .map((i) => containerNameFromBacklog(i.backlog))
  ),
  items: ensureUniquePriorities(SEED_RAW.items),
};
