import { AppState, addWeeks, mondayOf, ensureUniquePriorities } from "./model";

const S0 = mondayOf();
const S1 = addWeeks(S0, 1);
const S2 = addWeeks(S0, 2);
const S3 = addWeeks(S0, 3);
const S4 = addWeeks(S0, 4);
const S6 = addWeeks(S0, 6);
const S8 = addWeeks(S0, 8);

/** Demo: mix of 1 / 2 / 3+ teams with per-team start dates */
const SEED_RAW: AppState = {
  version: 3,
  startDate: S0,
  teams: [
    {
      id: "platform",
      name: "Platform",
      capacityPw: 4,
      color: "#d60000",
    },
    {
      id: "mobile",
      name: "Mobile",
      capacityPw: 3,
      color: "#455a64",
    },
    {
      id: "data",
      name: "Data & Analytics",
      capacityPw: 2.5,
      color: "#737373",
    },
    {
      id: "crm",
      name: "CRM / Sales Tech",
      capacityPw: 3.5,
      color: "#e65100",
    },
  ],
  items: [
    {
      id: "p2",
      title: "Мобильный чекаут v2",
      type: "product",
      backlog: "Product backlog · Mobile",
      assignments: [{ teamId: "mobile", size: "M", workStartDate: S0 }],
      status: "ready",
      owner: "Маша Л.",
      businessValue: 8,
      timeCriticality: 5,
      riskReduction: 5,
      jobSize: 6,
      manualRank: null,
    },
    {
      id: "j4",
      title: "Интеграция телефонии для отдела продаж",
      type: "project",
      backlog: "Projects backlog · Sales Ops",
      assignments: [{ teamId: "crm", size: "S", workStartDate: S1 }],
      status: "ready",
      owner: "Сергей М.",
      businessValue: 7,
      timeCriticality: 7,
      riskReduction: 3,
      jobSize: 3,
      manualRank: null,
    },
    {
      id: "p6",
      title: "Push-уведомления и deep links",
      type: "product",
      backlog: "Product backlog · Mobile",
      assignments: [{ teamId: "mobile", size: "S", workStartDate: S4 }],
      status: "idea",
      owner: "Маша Л.",
      businessValue: 6,
      timeCriticality: 4,
      riskReduction: 2,
      jobSize: 3,
      manualRank: null,
    },
    {
      id: "j6",
      title: "Дашборд KPI для совета директоров",
      type: "project",
      backlog: "Projects backlog · Exec",
      assignments: [{ teamId: "data", size: "S", workStartDate: S0 }],
      status: "ready",
      owner: "Павел Р.",
      businessValue: 8,
      timeCriticality: 9,
      riskReduction: 2,
      jobSize: 2,
      notes: "Нужен к ближайшему совету",
      manualRank: null,
    },
    {
      id: "p5",
      title: "Админ-панель ролей и аудита",
      type: "product",
      backlog: "Product backlog · Platform",
      assignments: [{ teamId: "platform", size: "S", workStartDate: S6 }],
      status: "idea",
      owner: "Аня К.",
      businessValue: 5,
      timeCriticality: 2,
      riskReduction: 8,
      jobSize: 4,
      manualRank: null,
    },
    {
      id: "p1",
      title: "Единый каталог цен и остатков",
      type: "product",
      backlog: "Product backlog · Commerce",
      assignments: [
        { teamId: "platform", size: "M", workStartDate: S0 },
        { teamId: "data", size: "M", workStartDate: S3 },
      ],
      status: "in_progress",
      owner: "Аня К.",
      businessValue: 9,
      timeCriticality: 7,
      riskReduction: 6,
      jobSize: 8,
      notes: "Data стартует после первых API Platform",
      manualRank: null,
    },
    {
      id: "j1",
      title: "Внедрение EDI для крупного B2B-клиента",
      type: "project",
      backlog: "Projects backlog · Delivery",
      assignments: [
        { teamId: "platform", size: "M", workStartDate: S1 },
        { teamId: "crm", size: "S", workStartDate: S4 },
      ],
      status: "ready",
      owner: "Игорь С.",
      businessValue: 8,
      timeCriticality: 9,
      riskReduction: 4,
      jobSize: 5,
      notes: "CRM — онбординг после ядра EDI",
      manualRank: null,
    },
    {
      id: "j2",
      title: "Пилот Launchpad: клинический портал",
      type: "project",
      backlog: "Projects backlog · Launchpad",
      assignments: [
        { teamId: "mobile", size: "M", workStartDate: S2 },
        { teamId: "platform", size: "S", workStartDate: S2 },
      ],
      status: "ready",
      owner: "Денис В.",
      businessValue: 7,
      timeCriticality: 8,
      riskReduction: 7,
      jobSize: 4,
      notes: "Обе команды стартуют одновременно",
      manualRank: null,
    },
    {
      id: "j3",
      title: "Миграция отчётности клиента X на DWH",
      type: "project",
      backlog: "Projects backlog · Data",
      assignments: [
        { teamId: "data", size: "M", workStartDate: S1 },
        { teamId: "platform", size: "S", workStartDate: S0 },
      ],
      status: "ready",
      owner: "Павел Р.",
      businessValue: 6,
      timeCriticality: 6,
      riskReduction: 8,
      jobSize: 5,
      notes: "Platform — пайплайн выгрузки раньше Data",
      manualRank: null,
    },
    {
      id: "p4",
      title: "Сквозная воронка лида → сделка",
      type: "product",
      backlog: "Product backlog · CRM",
      assignments: [
        { teamId: "crm", size: "M", workStartDate: S0 },
        { teamId: "platform", size: "S", workStartDate: S2 },
        { teamId: "mobile", size: "S", workStartDate: S6 },
      ],
      status: "in_progress",
      owner: "Оля Т.",
      businessValue: 9,
      timeCriticality: 6,
      riskReduction: 5,
      jobSize: 6,
      notes: "Mobile подключается после событий Platform",
      manualRank: null,
    },
    {
      id: "j5",
      title: "Compliance-пакет HIPAA для продукта Y",
      type: "project",
      backlog: "Projects backlog · Security",
      assignments: [
        { teamId: "platform", size: "M", workStartDate: S3 },
        { teamId: "data", size: "S", workStartDate: S4 },
        { teamId: "mobile", size: "S", workStartDate: S8 },
      ],
      status: "blocked",
      owner: "Игорь С.",
      businessValue: 8,
      timeCriticality: 8,
      riskReduction: 9,
      jobSize: 6,
      notes: "Ждём юристов; старты сдвинуты",
      manualRank: null,
    },
    {
      id: "p3",
      title: "Рекомендации в поиске (ML)",
      type: "product",
      backlog: "Product backlog · Growth",
      assignments: [
        { teamId: "data", size: "L", workStartDate: S2 },
        { teamId: "platform", size: "S", workStartDate: S6 },
        { teamId: "mobile", size: "S", workStartDate: S8 },
      ],
      status: "idea",
      owner: "Катя Н.",
      businessValue: 7,
      timeCriticality: 3,
      riskReduction: 6,
      jobSize: 7,
      notes: "Serving и UI после модели",
      manualRank: null,
    },
  ],
};

/** Unique priorities assigned by WSJF (1 = highest) */
export const SEED: AppState = {
  ...SEED_RAW,
  items: ensureUniquePriorities(SEED_RAW.items),
};
